name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mne mne-bids autoreject mne-icalabel meegkit pyyaml matplotlib pytest



      - name: Run tests
        run: |
          export PYTHONPATH=$PWD
          pytest -q